changes made for dts from 21.02 branch

diff --git a/target/linux/sunxi/base-files/etc/uci-defaults/99_tlink b/target/linux/sunxi/base-files/etc/uci-defaults/99_tlink
--- a/target/linux/sunxi/base-files/etc/uci-defaults/99_tlink
+++ b/target/linux/sunxi/base-files/etc/uci-defaults/99_tlink
@@ -70,13 +70,13 @@ tlink_add_4g_wan() {
 	uci set network.4g_wan='interface'
 	uci set network.4g_wan.service='umts'
 	uci set network.4g_wan.proto='3g'
-	uci set network.4g_wan.device=$(AT_PORT)
+	uci set network.4g_wan.device=${AT_PORT}
 	uci set network.4g_wan.ipv6='auto'
 	uci set network.4g_wan.apn='3gnet'
 	uci set network.4g_wan.metric='10'
 	uci commit network
 
-	uci set 3ginfo.@3ginfo[0].device=$(AT_PORT_INFO)
+	uci set 3ginfo.@3ginfo[0].device=${AT_PORT_INFO}
 	uci commit 3ginfo
 
 	uci set system.led_modem.dev='3g-4g_wan'
@@ -146,6 +146,23 @@ tlink_sd_default () {
 	fi
 }
 
+tlink_init_4g() {
+	[ -e /dev/cdc-wdm0 ] && {
+		# QMI interface
+		echo "QMI module found!!!" > /dev/console
+		tlink_add_qmi_interface
+	} || {
+		echo "QMI module not found!!!" > /dev/console
+		tlink_add_4g_wan
+	}
+}
+
+tlink_init_5g() {
+	board_config_update
+	ucidef_set_interface "5g_wan" device "usb0" protocol "dhcp"
+	board_config_flush
+}
+
 tlink_default() {
 	# tlink_sd_default
 
@@ -156,14 +173,14 @@ tlink_default() {
 		echo "Data mount added"
 	fi
 
-	[ -e /dev/cdc-wdm0 ] && {
-		# QMI interface
-		echo "QMI module found!!!" > /dev/console
-		tlink_add_qmi_interface
-	} || {
-		echo "QMI module not found!!!" > /dev/console
-		tlink_add_4g_wan
-	}
+	case "$(board_name)" in
+		"kooiot,tlink-k2")
+			tlink_init_5g
+			;;
+		*)
+			tlink_init_4g
+			;;
+	esac
 
 	# ETH MAC for usb-eth mac been set in board.d/02_network
 	#case "$(board_name)" in
