sunxi: support ThingsLink E2
which is an e1 based board, but few gpio changed

diff --git a/target/linux/sunxi/base-files/etc/board.d/02_network b/target/linux/sunxi/base-files/etc/board.d/02_network
--- a/target/linux/sunxi/base-files/etc/board.d/02_network
+++ b/target/linux/sunxi/base-files/etc/board.d/02_network
@@ -32,6 +32,19 @@ sunxi_setup_interfaces()
 			ucidef_set_interface_lan "eth0"
 		fi
 		;;
+	kooiot,tlink-e2)
+		# detect WCH297 usb-eth
+		lsusb -d "1a86:5397" > /dev/null
+		if [ $? -eq 0 ]; then
+			echo "CH397 USB-ETH found!" > /dev/kmsg
+			# ucidef_set_interfaces_lan_wan "eth0" "eth1"
+			ucidef_set_interface_lan "eth0"
+			ucidef_set_interface "lan2" device "eth1" protocol "static"
+		else
+			echo "CH397 USB-ETH not found found!" > /dev/kmsg
+			ucidef_set_interface_lan "eth0"
+		fi
+		;;
 	kooiot,tlink-k1)
 		ucidef_set_interface_lan "eth0 eth1"
 		;;
@@ -120,7 +133,8 @@ sunxi_setup_macs()
 		;;
 	kooiot,tlink-s1|\
 	kooiot,tlink-e1-v0|\
-	kooiot,tlink-e1)
+	kooiot,tlink-e1|\
+	kooiot,tlink-e2)
 		# lan_mac=$(get_mac_binary "/sys/bus/i2c/devices/0-0050/eeprom" 0x20)
 		lan_mac=$(tlink_s1_gen_mac)
 		wan_mac=$(macaddr_add "$lan_mac" 1)
