support psn parser

diff --git a/target/linux/ramips/mt76x8/base-files/sbin/write_psn b/target/linux/ramips/mt76x8/base-files/sbin/write_psn
--- a/target/linux/ramips/mt76x8/base-files/sbin/write_psn
+++ b/target/linux/ramips/mt76x8/base-files/sbin/write_psn
@@ -34,8 +34,19 @@ if [ $# -eq 0 ]; then
 	exit 1
 fi
 
+if [ -f /lib/functions/psn/parser.sh ] ; then
+	. /lib/functions/psn/parser.sh
+	echo "PSN SRC: ${psn}"
+
+	psn="$(product_sn_encode ${psn})"
+	if [ ${#psn} -le 8 ]; then
+		echo "Product Serial Number encode failed!"
+		exit 3
+	fi
+fi
+
 if [ ${#psn} -ne 16 ]; then
-	echo "Product Serial Number must be 16 characters"
+	echo "Product Serial Number must be 16 characters!"
 	exit 2
 fi
 
@@ -54,7 +65,10 @@ echo ""
 #----------------------------------------------------------
 
 
-NVMEM_PATH="/sys/devices/platform/soc/1c2ac00.i2c/i2c-0/0-0050/0-00500/nvmem"
+NVMEM_PATH="/sys/bus/i2c/devices/0-0050/eeprom"
+if [ ! -f ${NVMEM_PATH} ]; then
+	NVMEM_PATH="/sys/bus/i2c/devices/0-0050/0-00501/nvmem"
+fi
 
 if [ ! -f ${NVMEM_PATH} ]; then
     echo "Product SN in FACTORY mtd partition!!!"
@@ -90,6 +104,7 @@ else
 fi
 
 if [ "${product_sn}"x = "${product_sn_dp}"x ]; then
+	echo "${product_sn}" > /tmp/sysinfo/product_sn
 	echo "Loaded PSN: ${product_sn}"
 
 	echo "Done!"
diff --git a/target/linux/sunxi/base-files/sbin/write_psn b/target/linux/sunxi/base-files/sbin/write_psn
--- a/target/linux/sunxi/base-files/sbin/write_psn
+++ b/target/linux/sunxi/base-files/sbin/write_psn
@@ -30,8 +30,19 @@ if [ $# -eq 0 ]; then
 	exit 1
 fi
 
+if [ -f /lib/functions/psn/parser.sh ] ; then
+	. /lib/functions/psn/parser.sh
+	echo "PSN SRC: ${psn}"
+
+	psn="$(product_sn_encode ${psn})"
+	if [ ${#psn} -le 8 ]; then
+		echo "Product Serial Number encode failed!"
+		exit 3
+	fi
+fi
+
 if [ ${#psn} -ne 16 ]; then
-	echo "Product Serial Number must be 16 characters"
+	echo "Product Serial Number must be 16 characters!"
 	exit 2
 fi
 
@@ -82,6 +93,7 @@ else
 fi
 
 if [ "${product_sn}"x = "${product_sn_dp}"x ]; then
+	echo "${product_sn}" > /tmp/sysinfo/product_sn
 	echo "Loaded PSN: ${product_sn}"
 
 	echo "Done!"
