write mac script and merge base files from master

diff --git a/target/linux/sunxi/base-files/sbin/write_psn b/target/linux/sunxi/base-files/sbin/write_psn
--- a/target/linux/sunxi/base-files/sbin/write_psn
+++ b/target/linux/sunxi/base-files/sbin/write_psn
@@ -1,68 +1,76 @@
 #!/bin/sh
 
-psn=$1
-
 . /lib/functions.sh
 . /lib/functions/tlink.sh
 
-case "$(board_name)" in
-"kooiot,tlink-x1" | \
-"kooiot,tlink-x1s" | \
-"kooiot,tlink-x3" | \
-"kooiot,tlink-x2" | \
-"kooiot,tlink-k1" | \
-"kooiot,tlink-s1" | \
-"kooiot,tlink-m408" | \
-"kooiot,tlink-m416" | \
-"kooiot,tlink-r1")
-	;;
-*)
-	echo "This only support ThingsLink devices"
-	exit 1
-	;;
-esac
+export FORCE=0
+export OFFSET=0
+export HELP=0
 
-show_help(){
+# parse options
+while [ -n "$1" ]; do
+	case "$1" in
+		-o) export OFFSET="$2"; shift;;
+		-f|--force) export FORCE=1;;
+		-h|--help) export HELP=1;;
+		-*)
+			echo "Invalid option: $1" >&2
+			exit 1
+		;;
+		*) break;;
+	esac
+	shift;
+done
+
+PSN="$1"
+if [ -z "${PSN}" ]; then
+	export HELP=1
+fi
+
+if [ $HELP -ne 0 ]; then
     cat <<EOF
-${0} <psn>
-EOF
-}
+Usage:	${0} [<write-option>...] <mac_base>
 
-if [ $# -eq 0 ]; then
-	show_help()
+write-option:
+	-o <offset>   Offset for writing mac
+	-f | --force  Force write without confirmation
+	-h | --help   Show help
+EOF
 	exit 1
 fi
 
 if [ -f /lib/functions/psn/parser.sh ] ; then
 	. /lib/functions/psn/parser.sh
-	echo "PSN SRC: ${psn}"
+	echo "PSN SRC: ${PSN}"
 
-	psn="$(product_sn_encode ${psn})"
-	if [ ${#psn} -le 8 ]; then
+	PSN="$(product_sn_encode ${PSN})"
+	if [ ${#PSN} -le 8 ]; then
 		echo "Product Serial Number encode failed!"
 		exit 3
 	fi
 fi
 
-if [ ${#psn} -ne 16 ]; then
+if [ ${#PSN} -ne 16 ]; then
 	echo "Product Serial Number must be 16 characters!"
 	exit 2
 fi
 
-echo "PSN: ${psn}"
-#----------------------------------------------------------
-echo ""
-echo -n "WARNING: PRODUCT SERIAL NUMBER REPLACED !, Continue (y/N)?  "
-read -n 1 ANSWER
+echo "PSN: ${PSN}"
 
-if [ ! "${ANSWER}" = "y" ] ; then
-    echo "."
-    echo "Canceled.."
-    exit 0
+if [ ${FORCE} -eq 0 ]; then
+	#----------------------------------------------------------
+	echo ""
+	echo -n "WARNING: PRODUCT SERIAL NUMBER REPLACED !, Continue (y/N)?  "
+	read -n 1 ANSWER
+
+	if [ ! "${ANSWER}" = "y" ] ; then
+		echo "."
+		echo "Canceled.."
+		exit 0
+	fi
+	echo ""
+	#----------------------------------------------------------
 fi
-echo ""
-#----------------------------------------------------------
-
 
 NVMEM_PATH="/sys/bus/i2c/devices/0-0050/eeprom"
 if [ ! -f ${NVMEM_PATH} ]; then
@@ -72,8 +80,8 @@ fi
 if [ ! -f ${NVMEM_PATH} ]; then
     echo "EEPROM not found! Product SN will be writen to EMMC!!!"
 
-	echo ${psn} | dd of=/dev/mmcblk1 count=16 bs=1 seek=410112
-	echo ${psn} | dd of=/dev/mmcblk1 count=16 bs=1 seek=410128
+	echo ${PSN} | dd of=/dev/mmcblk1 count=16 bs=1 seek=410112
+	echo ${PSN} | dd of=/dev/mmcblk1 count=16 bs=1 seek=410128
 
 	product_sn=$(dd if=/dev/mmcblk1 \
 		bs=1 count=16 skip=410112 2>/dev/null | \
@@ -83,8 +91,8 @@ if [ ! -f ${NVMEM_PATH} ]; then
 		bs=1 count=16 skip=410128 2>/dev/null | \
 		hexdump -v -e '/1 "%c"' 2>/dev/null)
 else
-	echo ${psn} | dd of=${NVMEM_PATH} count=16 bs=1 seek=0
-	echo ${psn} | dd of=${NVMEM_PATH} count=16 bs=1 seek=16
+	echo ${PSN} | dd of=${NVMEM_PATH} count=16 bs=1 seek=0
+	echo ${PSN} | dd of=${NVMEM_PATH} count=16 bs=1 seek=16
 
 	product_sn=$(dd if=${NVMEM_PATH} \
 		bs=1 count=16 skip=0 2>/dev/null | \
